variables:
  - name: function_name
    ask: Name of the function
  - name: category
    ask: Documentation category (lower case)
  - name: unstable_apis
    default_value: "false"
    ask: Does the function require `--cfg=web_sys_unstable_apis` to be activated?
    select_in_values: ["true", "false"]
  - name: module
    default_value: ""
    ask: Module [optional]
  - name: feature
    default_value: "{{ function_name }}"
    ask: cfg feature

ignores:
  - modify_files.py
  - createfn.sh

scripts:
  - cmd: python3 template/modify_files.py {{ function_name }} {{ category }}{{#if module}} --module {{ module }}{{/if}} --feature {{ feature }} --unstable_apis {{ unstable_apis }}
